import React, { Component } from 'react'

export class God_head extends Component {
    render() {
        return (
            <div className='Godhead'>
                <img
                className='godhead-page-topic-pic'
                height='1120'
                alt='god-head'
                src='godhead6.webp'>
                </img>
                <h1>The Supreme Personality of GodHead</h1>
                <p className='consciouse-text'>The Personality of Godhead is perfect and complete. And because He is completely perfect, all emanations from Him, such as this phenomenal world, are perfectly equipped as a complete whole.
                    Whatever is produced of the complete whole is also complete by itself. And because He is the Complete Whole, even though so many complete units emanate from Him, He remains a complete balance.
                    Everything animate or inanimate that is within the universe is controlled and owned by the Lord. One should therefore accept only those things necessary for himself, which are set aside as his quota, and one must not
                    accept other things, knowing well to Whom they belong.
                </p>
                <p className='consciouse-text'>The Complete Whole, or the Supreme Absolute Truth, is the complete Personality of Godhead. Impersonal Brahman forms an incomplete realization of the Absolute Complete, and so also does the conception of Paramātman,
                    the Supersoul. The Supreme Personality of Godhead is impersonal Brahman realization is the realization of His sat or eternity aspect, and Supersoul realization, is the realization of His sat and cit, eternity and knowledge
                    aspects. But the realization of the Personality of Godhead is the realization of all the transcendental features, sat, cit, and bliss. In the Personal concept, this is realized incomplete form. And so the Complete Whole is
                    not formless. If He is formless, or if He is less than His creation in any other thing, He cannot be complete. The Complete Whole must have everything, both within our experience and beyond our experience. Otherwise,
                    He cannot be complete. The Complete Whole Personality of Godhead has immense potencies, and all of them are as complete as He is. Therefore this phenomenal or material world is also complete by itself. The twenty-four
                    elements of which this material universe is a temporary manifestation are completely adjusted to produce complete things necessary for the maintenance and subsistence of this universe. No extraneous effort by any other
                    unit is required for this maintenance. The universe has its own time, fixed by the energy of the Complete Whole, and when that time is complete this temporary manifestation will be annihilated by the complete arrangement
                    of the Complete. There is a complete facility for the small complete units, namely the living beings, to realize the Complete; and all forms of incompleteness are experienced only on account of incomplete knowledge of the Complete.
                    The human form of life is a complete manifestation of the consciousness of the living being, which is obtained after evolving through 8,400,000 species of life in the cycle of birth and death. If a human being does not realize his
                    completeness within the Complete in this life of full consciousness, he loses the chance of realizing his completeness and is put again into the cycle of evolution by the law of material Nature. Because we do not know that there is
                    a complete arrangement in nature for our maintenance, we make efforts to utilize the sources of Nature to create a so-called complete life of sense enjoyment. This misleading life of sense-enjoyment is called illusion because the
                    living entity cannot enjoy the life of the senses without being dovetailed with the Complete Whole.
                </p>
                <p className='consciouse-text'>For example, the hand of a body is a complete unit as long as it is attached to the complete body. When the hand is detached from the body, it may appear like a hand, but actually, it has none of the potency of a hand. Similarly, the living beings
                    are parts and parcels of the Complete Whole; and as long as the parts and parcels are detached from the Complete Whole, the illusory representation of completeness is not enough to bring the desired result. The completeness of human life can only
                    be realized when the human form of life is engaged in the service of the Complete Whole. Any service in this world, whether social, political, communal, international, or even inter-planetary, will remain incomplete unless and until it is dovetailed
                    with the Complete Whole. And, when everything is dovetailed with the Complete Whole, the attached parts and parcels also become complete in themselves.
                    The person who was lost before did not know what he truly was now found himself he now has become the complete truth from that rest within the lord. He now knows why everything exists and what Reality is made out of.  Which is Consciousness or Awareness of God itself. 
                </p>
                <p className='godhead-subtitle'>Beyond Birth and Death</p>
                <p className='consciouse-text'>This topic will try to hit on person Consciousness before their birth and after their death. I will try to guide you towards your true nature that is every lasting and forever free so here we go: 
                    A living being, especially a civilized man, has a natural desire to live forever in happiness. This is quite natural because, in his original state, the living being is both eternal and joyful. However, in the present conditioned state of life, he is engaged in a struggle against
                    recurring birth and death. Therefore he has attained neither happiness nor immortality. The latest desire man has developed is the desire to travel to other planets. This is also quite natural because he has the constitutional right to go to any part of the material or spiritual
                    skies. Such travel is very tempting and exciting because these skies are full of unlimited globes of varying qualities, and they are occupied by all types of living entities. The desire to travel there can be fulfilled by the process of yoga, which serves as a means by which one
                    can transfer himself to whatever planet he likes-possibly to planets where life is not only eternal and blissful but where there are multiple varieties of enjoyable energies. Anyone who can attain the freedom of the spiritual planets needs never return to this miserable land of
                    birth, old age, disease, and death. One can attain this stage of perfection very easily by his individual effort. He can simply follow, in his own home, the prescribed method of bhakti-yoga. This method, under proper guidance, is simple and enjoyable. An attempt is made herein
                    to give information to the people in general, and to philosophers and religionists in particular, as to how one can transfer oneself to other planets by this process of bhakti-yoga-the highest of all yogic processes.
                </p>
                <p className='godhead-subtitle'>The Bhagavad Gita passage of  Lord Krishna</p>
                <p className='consciouse-text'> Some of this text is from the book Bhagavad Gita as it is by A. C. Bhaktivedanta the text is trying to communicate to you the essence of who you truly are through this teaching so here we go:
                 “O descendant of Bharata, he who dwells in the body is eternal and can never be slain. Therefore you need not grieve for any creature.”
                </p>
                <p className='consciouse-text'>The very first step in self-realization is realizing one’s identity as separate from the body. “I am not this body but am a spirit soul” is an essential realization for anyone who wants to transcend death and enter into the spiritual world beyond. It is not simply a matter of saying
                    “I am not this body,” but of actually realizing it. This is not as simple as it may seem at first. Although we are not these bodies but are pure consciousness, somehow or other we have become encased within the bodily dress. If we actually want the happiness and independence that
                    transcend death, we have to establish ourselves and remain in our constitutional position as pure consciousness. Living in the bodily conception, our idea of happiness is like that of a man in delirium. Some philosophers claim that this delirious condition of bodily identification should
                    be cured by abstaining from all action. Because these material activities have been a source of distress for us, they claim that we should actually stop these activities. Their culmination of perfection is in a kind of Buddhistic nirvāṇa, in which no activities are performed. Buddha maintained that
                    due to a combination of material elements, this body has come into existence and that somehow or other if these material elements are separated or dismantled, the cause of suffering is removed. If the tax collectors give us too much difficulty because we happen to possess a large house, one simple solution
                    is to destroy the house. However, the Bhagavad-gita indicates that this material body is not all in all. Beyond this combination of material elements, there is spirit, and the symptom of that spirit is consciousness.
                </p>
               <p className='consciouse-text'>Consciousness cannot be denied. A body without consciousness is a dead body. As soon as consciousness is removed from the body, the mouth will not speak, the eye will not see, nor the ears hear. A child can understand that. It is a fact that consciousness is absolutely necessary for the
                    animation of the body. What is this consciousness? Just as heat or smoke are symptoms of fire, so consciousness is the symptom of the soul. The energy of the soul, or self, is produced in the shape of consciousness. Indeed, consciousness proves that the soul is present. This is not only the philosophy of the Bhagavad-gita
                    but the conclusion of all Vedic literature. The impersonalist followers of Śaṅkarācārya, as well as the Vaiṣṇavas following in the disciplic succession from Lord Sri Krishna, acknowledge the factual existence of the soul, but the Buddhist philosophers do not. The Buddhists contend that at a certain stage the combination
                    of matter produces consciousness, but this argument is refuted by the fact that although we may have all the constituents of matter at our disposal, we cannot produce consciousness from them. All the material elements may be present in a dead man, but we cannot revive that man to consciousness. This body is not like a machine.
                    When a part of a machine breaks down, it can be replaced, and the machine will work again, but when the body breaks down and consciousness leaves the body, there is no possibility of our replacing the broken part and rejuvenating the consciousness. The soul is different from the body, and as long as the soul is there, the
                    body is animate. But there is no possibility of making the body animate in the absence of the soul. Because we cannot perceive the soul by our gross senses, we deny it. Actually, there are so many things that are there which we cannot see. We cannot see air, radio waves, or sound, nor can we perceive minute bacteria with our
                    blunt senses, but this does not mean they are not there. With the aid of the microscope and other instruments, many things can be perceived which had previously been denied by the imperfect senses. Just because the soul, which is atomic in size, has not been perceived yet by senses or instruments, we should not conclude
                    that it is not there. It can, however, be perceived by its symptoms and effects.</p>
                <p className='consciouse-text'>In the Bhagavad-gita Sri Krishna points out that all of our miseries are due to false identification with the body. 
                “O son of Kuntī, the nonpermanent appearance of heat and cold, happiness and distress, and their disappearance in due course are like the appearance and disappearance of winter and summer seasons. They arise from sense perception, O scion of Bharata, and one must learn to tolerate them without being disturbed.”
                </p>
                <p className='consciouse-text'>In the summertime, we may feel pleasure from contact with water, but in the winter we may shun that very water because it is too cold. In either case, the water is the same, but we perceive it as pleasant or painful due to its contact with the body. All feelings of distress and happiness are due to the body.
                    Under certain conditions, the body and mind feel happiness and distress. Factually we are hankering after happiness, for the soul’s constitutional position is that of happiness. The soul is part and parcel of the Supreme Being, who is the embodiment of knowledge, bliss, and eternity. Indeed, the very name Krishna, which is nonsectarian,
                     means “the greatest pleasure.” Krishna means “greatest” and ṇa means “pleasure.” Krishna is the epitome of pleasure, and being part and parcel of Him, we hanker for pleasure. A drop of ocean water has all the properties of the ocean itself, and we, although minute particles of the Supreme Whole, have the same energetic properties as the Supreme.</p>
                <p className='consciouse-text'>The atomic soul, although so small, is moving the entire body to act in so many wonderful ways. In the world we see so many cities, highways, bridges, great buildings, monuments, and great civilizations, but who has done all this? It is all done by the minute spirit spark within the body. If such wonderful things can be performed by
                    the minute spirit spark, we cannot begin to imagine what can be accomplished by the Supreme Spirit Whole. The natural hankering of the minute spirit spark is for the qualities of the whole – knowledge, bliss, and eternality – but these hankerings are being frustrated due to the material body. At present we are trying to attain
                    eternity, bliss, and knowledge by means of an imperfect instrument. Actually, our progress toward these goals is being blocked by the material body; therefore we have to come to the realization of our existence beyond the body. Theoretical knowledge that we are not these bodies will not do. We have to keep ourselves always separate
                    as masters of the body, not as servants. If we know how to drive a car well, it will give us good service; but if we do not know how we will be in danger. The body is composed of senses, and the senses are always hungry after their objects. The eyes see a beautiful person and tell us, “Oh, there is a beautiful girl, a beautiful boy.
                    Let’s go see.” The ears are telling us, “Oh, there is very nice music. Let us go hear it.” The tongue is saying, “Oh, there is a very nice restaurant with palatable dishes. Let us go.” In this way, the senses are dragging us from one place to another, and because of this, we are perplexed.
                </p>
                <p className='consciouse-text'>“As a boat on the water is swept away by a strong wind, even one of the senses on which the mind focuses can carry away a man’s intelligence.” It is imperative that we learn how to control the senses. The name gosvāmī is given to someone who has learned how to master the senses. Go means “senses,” and “controller”;
                    so one who can control the senses is to be considered. Krishna indicates that one who identifies with the illusory material body cannot establish himself in his proper identity as a spirit soul. Bodily pleasure is flickering and intoxicating, and we cannot actually enjoy it, because of its momentary nature. Actual pleasure is of the soul, not
                    the body. We have to mold our lives in such a way that we will not be diverted by bodily pleasure. If somehow we are diverted, it is not possible for us to establish our consciousness in its true identity beyond the body.
                </p>
                <p className='consciouse-text'>“In the minds of those who are too attached to sense enjoyment and material opulence, and who are bewildered by such things, the resolute determination for devotional service to the Supreme Lord does not take place. The Vedas deal with the subject of the three modes of material nature. Rise above these modes, O Arjuna. Be transcendental to all of them.
                    Be free from all dualities and from all anxieties for gain and safety, and be established in the Self.”
                </p>
                <p className='consciouse-text'>The word Veda means “book of knowledge.” There are many books of knowledge, which vary according to the country, population, environment, etc. In India, the books of knowledge are referred to as the Vedas. In the West, they are called the Old Testament and New Testament. The Muhammadans accept the Koran. What is the purpose of all these books of knowledge?
                    They are to train us to understand our position as a pure soul. Their purpose is to restrict bodily activities by certain rules and regulations, and these rules and regulations are known as codes of morality. The Bible, for instance, has ten commandments intended to regulate our lives. The body must be controlled in order for us to reach the highest perfection,
                    and without regulative principles, it is not possible to perfect our lives. The regulative principles may differ from country to country or from scripture to scripture, but that doesn’t matter, for they are made according to the time and circumstances and the mentality of the people. But the principle of regulated control is the same. Similarly, the government sets
                    down certain regulations to be obeyed by its citizens. There is no possibility of making advancements in government or civilization without some regulations. In the previous verse, Sri Krishna tells Arjuna that the regulative principles of the Vedas are meant to control the three modes of material nature – goodness, passion, and ignorance. However, Krishna is
                    advising Arjuna to establish himself in his pure constitutional position as a spirit soul, beyond the dualities of material nature.
                </p>
                <p className='consciouse-text'>As we have already pointed out, these dualities – such as heat and cold, pleasure and pain – arise due to the contact of the senses with their objects. In other words, they are born of identification with the body. Krishna indicates that those who are devoted to enjoyment and power are carried away by the words of the Vedas, which
                    promise heavenly enjoyment by sacrifice and regulated activity. Enjoyment is our birthright, for it is the characteristic of the spirit soul, but the spirit soul tries to enjoy materially, and this is the mistake. Everyone is turning to material subjects for enjoyment and is compiling as much knowledge as possible. Someone is becoming a chemist, physicist, politician,
                    artist, or whatever. Everyone knows something of everything or everything of something, and this is generally known as knowledge. But as soon as we leave the body, all of this knowledge is vanquished. In a previous life, one may have been a great man of knowledge, but in this life, he has to start again by going to school and learning how to read and write from the
                    beginning. Whatever knowledge was acquired in the previous life is forgotten. The situation is that we are actually seeking eternal knowledge, but this cannot be acquired by this material body. We are all seeking enjoyment through these bodies, but bodily enjoyment is not our actual enjoyment. It is artificial. We have to understand that if we want to continue in
                    this artificial enjoyment, we will not be able to attain our position of eternal enjoyment.
                </p>
                <p className='consciouse-text'>The body must be considered a diseased condition. A diseased man cannot enjoy himself properly; a man with jaundice, for instance, will taste sugar candy as bitter, but a healthy man can taste its sweetness. In either case, the sugar candy is the same, but according to our condition, it tastes different. Unless we are cured of this diseased
                    conception of bodily life, we cannot taste the sweetness of spiritual life. Indeed, it will taste bitter to us. At the same time, by increasing our enjoyment of material life, we are further complicating our diseased condition. A typhoid patient cannot eat solid food, and if someone gives it to him to enjoy, and he eats it, he is further complicating his malady and is
                    endangering his life. If we really want freedom from the miseries of material existence, we must minimize our bodily demands and pleasures.
                </p>
                <p className='consciouse-text'>Actually, material enjoyment is not enjoyment at all. Real enjoyment does not cease. In the Mahābhārata there is a verse to the effect that the yogis, those who are endeavoring to elevate themselves to the spiritual platform, are actually enjoying, but their enjoyment is endless. This is because their enjoyment is in relation to the supreme
                    enjoyer, Sri Krishna. Sri Krishna is the real enjoyer, and the Bhagavad-gita  confirms this: “The sages, knowing Me as the ultimate enjoyer of all sacrifices and austerities, the Supreme Lord of all planets and demigods, and the benefactor and well-wisher of all living entities, attain peace from the pangs of material miseries.”
                    our enjoyment comes from understanding our position as the enjoyed it. The real enjoyer is the Supreme Lord, and we are enjoyed by Him.
                </p>
                <p className='consciouse-text'>An example of this relationship can be found in the material world between the husband and the wife: the husband is the enjoyer (puruṣa), and the wife is the enjoyed (prakṛti). The spirit is the subject, and prakṛti, or nature, is the object. The enjoyment, however, is participated in both by the husband and the wife. When actual enjoyment
                    is there, there is no distinction that the husband is enjoying more or the wife is enjoying less. Although the male is the predominator and the female is predominant, there is no division when it comes to enjoyment. On a larger scale, no living entity is the enjoyer. God expanded into many, and we constitute those expansions. God is one without a second, but He willed to
                    become many in order to enjoy. We have an experience that there is little or no enjoyment in sitting alone in a room talking to oneself. However, if there are five people present, our enjoyment is enhanced, and if we can discuss Krishna before many, many people, the enjoyment is all the greater. Enjoyment means variety. God became many for His enjoyment, and thus our
                    position is that of the enjoyed. That is our constitutional position and the purpose for our creation. Both enjoyer and enjoyer have consciousness, but the consciousness of the enjoyed is subordinate to the consciousness of the enjoyer. Although Krishna is the enjoyer and we enjoyed it, the enjoyment can be participated in equally by everyone. Our enjoyment can be
                    perfected when we participate in the enjoyment of God. There is no possibility of our enjoying separately on the bodily platform. Material enjoyment on the gross bodily platform is discouraged throughout the Bhagavad-gita. 
                </p>
                <p className='consciouse-text'>“O son of Kuntī, the nonpermanent appearance of heat and cold, happiness and distress, and their disappearance in due course are like the appearance and disappearance of winter and summer seasons. They arise from sense perception, O scion of Bharata, and one must learn to tolerate them without being disturbed.”
                    The gross material body is a result of the interaction of the modes of material nature, and it is doomed to destruction.
                    “Only the material body of the indestructible, immeasurable, and eternal living entity is subject to destruction; therefore, fight, O descendant of Bharata.”
                    Sri Krishna, therefore, encourages us to transcend the bodily conception of existence and attain to our actual spiritual life.
                    “When the embodied being is able to transcend these three modes [goodness, passion, and ignorance], he can become free from birth, death, old age, and their distresses and can enjoy nectar even in this life.”
                </p>
                <p className='consciouse-text'>To establish ourselves on the pure Brahman spiritual platform, above the three modes, we must take up the method of  Krishna consciousness. The gift of Caitanya Mahāprabhu, the chanting of the names of Sri Krishna – Hare Krishna, Hare Krishna, Krishna, Krishna, Hare Hare, Hare Rāma, Hare Rama, Rama Rama, Hare Hare – facilitates this process.
                    This method is called mantra-yoga, and it is employed by the highest transcendentalists. How the transcendentalists realize their identity beyond birth and death, beyond the material body, and transfer themselves from the material universe to the spiritual universes that are eternal. Therefore they are free for eternity just purely playing and enjoy with infinite others, Aman.  
                </p>
            </div>
        )
    }
}

export default God_head;